# Site settings
# =============
title: "Harsh Joshi"
tagline: Living life and its non linear moments.
email: me.harsh.joshi@gmail.com
description: "Personal website of Harsh Joshi and his rantings on DSP, ML and Chaos"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "http://Joshi-Harsh.github.io"

author:
  name: Harsh Joshi
  email: me.harsh.joshi@gmail.com
  url: http://Joshi-Harsh.github.io/about.html

github:
  repo: https://github.com/Joshi-Harsh/
twitter:
  username: me_harsh_joshi

google_analytics: UA-83656206-1

# Build settings
# ==============
source: ./
destination: ../Joshi-Harsh.github.io/



markdown: kramdown
highlighter: rouge

exclude:   [README.md, LICENSE.md]
permalink: none
timezone:  Asia/Calcutta
